trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 05MVC/NoteTakingApp
    - 06DevOps/azure-pipelines-notes-app.yml

pr: none

stages:
- stage: build
  jobs:
  - job: build

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: dotnet build
      displayName: dotnet build (script)
      workingDirectory: 05MVC/NoteTakingApp

    - task: DotNetCoreCLI@2
      displayName: dotnet build (task)
      inputs:
        command: 'build'
        projects: '05MVC/NoteTakingApp'

