trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 05MVC/NoteTakingApp
    - 06DevOps/azure-pipelines-notes-app.yml

pr: none

stages:
- stage: build
  jobs:

  - job: build_linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        debug:
          configuration: Debug
        release:
          configuration: Release
    steps:
    - script: dotnet build --configuration $(configuration)
      displayName: dotnet build
      workingDirectory: 05MVC/NoteTakingApp

  - job: build_windows_vs
    pool:
      vmImage: windows-latest
    steps:
    - task: NuGetCommand@2
      displayName: nuget restore
      inputs:
        command: 'restore'
        restoreSolution: '05MVC/NoteTakingApp/*.sln'
        feedsToUse: 'select'
    - task: VSBuild@1
      displayName: visual studio build
      inputs:
        solution: '05MVC\NoteTakingApp\*.sln'

  - job: build_cli
    pool:
      vmImage: windows-latest
    steps:
    - script: dotnet build
      displayName: dotnet build
      workingDirectory: 05MVC/NoteTakingApp

