trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 05MVC/NoteTakingApp
    - 06DevOps/azure-pipelines-notes-app.yml

pr: none

variables:
  slnPath: 05MVC/NoteTakingApp

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(slnPath)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(slnPath)