trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 05MVC/NoteTakingApp
    - 06DevOps/azure-pipelines-notes-app.yml

pr: none

stages:
- stage: build
  jobs:
  - job: build

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        pwd
        cd 05MVC
      displayName: cd

    - script: |
        pwd
      displayName: pwd
